### ISSUE TITLE
Arduino ide compiler problems

### ISSUE THREAD

**Issue by mobier** [MartyMacGyver/ESP32_Adafruit_ILI9341#2]
C:\Users\Administrator\Documents\Arduino\libraries\Adafruit_ILI9341\Adafruit_ILI9341.cpp: In member function 'void Adafruit_ILI9341::spiwrite(uint8_t)':

C:\Users\Administrator\Documents\Arduino\libraries\Adafruit_ILI9341\Adafruit_ILI9341.cpp:113:3: error: 'mosiport' was not declared in this scope

  *mosiport |=  mosipinmask;

   ^

C:\Users\Administrator\Documents\Arduino\libraries\Adafruit_ILI9341\Adafruit_ILI9341.cpp:113:16: error: 'mosipinmask' was not declared in this scope

  *mosiport |=  mosipinmask;

                ^

C:\Users\Administrator\Documents\Arduino\libraries\Adafruit_ILI9341\Adafruit_ILI9341.cpp:116:3: error: 'mosiport' was not declared in this scope

  *mosiport &= ~mosipinmask;

   ^

C:\Users\Administrator\Documents\Arduino\libraries\Adafruit_ILI9341\Adafruit_ILI9341.cpp:116:16: error: 'mosipinmask' was not declared in this scope

  *mosiport &= ~mosipinmask;

                ^

C:\Users\Administrator\Documents\Arduino\libraries\Adafruit_ILI9341\Adafruit_ILI9341.cpp:119:8: error: 'clkport' was not declared in this scope

       *clkport |=  clkpinmask;

        ^

C:\Users\Administrator\Documents\Arduino\libraries\Adafruit_ILI9341\Adafruit_ILI9341.cpp:119:20: error: 'clkpinmask' was not declared in this scope

       *clkport |=  clkpinmask;

                    ^

exit status 1
for ESP32 Dev Module

In Arduino ide 1.8.0 compiler on the emergence of the above problem

**Comment by MartyMacGyver** [comment]
Which ESP32 Dev Module? Also, if not the ESP-WROVER-KIT, are all the pins on your display wired up to GPIO ports? You cannot make any of the pins NULL... that will surely cause issues.
